// Generated by CoffeeScript 1.4.0
(function() {
  var Factory, GameWorld;

  GameWorld = (function() {

    function GameWorld(canvas) {
      this.canvas = canvas;
      this.then = null;
      this.factories = [];
      this.oxygen = 0;
    }

    GameWorld.prototype.render = function() {};

    GameWorld.prototype.update = function(modifier) {
      return console.log("Modifier: " + modifier + ", Oxygen: " + this.oxygen);
    };

    GameWorld.prototype.main = function() {
      var delta, now;
      now = Date.now();
      delta = now - this.then;
      this.update(1000);
      this.render();
      this.then = now;
      return true;
    };

    GameWorld.prototype.run = function() {
      var callback;
      this.then = Date.now();
      callback = this.main.bind(this);
      return setInterval(callback, 1);
    };

    GameWorld.prototype.add = function(object) {
      this.canvas.ctx.fillStyle = object.color;
      this.canvas.ctx.fillRect(object.x, object.y, object.width, object.height);
      return this.factories.push(object);
    };

    return GameWorld;

  })();

  Factory = (function() {

    function Factory(x, y) {
      this.x = x;
      this.y = y;
      this.height = 10;
      this.width = 10;
      this.color = '#00f';
      this.oxygen = 10;
    }

    return Factory;

  })();

  $(document).ready(function() {
    var canvas, gameWorld;
    canvas = {
      div: $('#canvas'),
      height: $('#canvas').height(),
      width: $('#canvas').width(),
      ctx: $('#canvas').get(0).getContext("2d")
    };
    gameWorld = new GameWorld(canvas);
    gameWorld.run();
    return canvas.div.live('click', function(e) {
      var factory;
      factory = new Factory(e.pageX, e.pageY);
      return gameWorld.add(factory);
    });
  });

}).call(this);
